=== AlexanderLasch/MKNetwork/wikiversum_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" vc:minVersion="1.1"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning">
    <xs:element name="TEI">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="teiHeader">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="fileDesc">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="titleStmt">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="title" type="xs:string"/>
                                                    <xs:element name="author" type="xs:string" minOccurs="0" maxOccurs="3"/>
                                                    <xs:element name="editor" type="xs:string" minOccurs="0" maxOccurs="3"/>
                                                    <xs:element name="respStmt" minOccurs="0" maxOccurs="5">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="resp" type="xs:string"/>
                                                                <xs:element name="name" type="xs:string" maxOccurs="5"/>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="extent">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="measure">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute name="unit" use="required" fixed="pages"/>
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="publicationStmt">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="publisher" type="xs:string" maxOccurs="3"/>
                                                    <xs:element name="pubPlace" type="xs:string"/>
                                                    <xs:element name="date" type="xs:string"/>
                                                    <xs:element name="idno" maxOccurs="5">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute name="type" use="required"/>
                                                                    <xs:attribute name="source" use="optional"/>
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="seriesStmt" maxOccurs="5">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="title" type="xs:string"/>

                                                    <xs:element name="biblScope">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute name="unit" use="required" fixed="pages"/>
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="idno" maxOccurs="5">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute name="type" use="required"/>
                                                                    <xs:attribute name="source" use="optional"/>
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="sourceDesc">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="bibl" type="xs:string"/>
                                                    <xs:element name="msDesc">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="msIdentifier">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                           <xs:element name="institution" type="xs:string"/>
                                                                           <xs:element name="idno" maxOccurs="5">
                                                                           <xs:complexType>
                                                                           <xs:simpleContent>
                                                                           <xs:extension base="xs:string">
                                                                           <xs:attribute name="type" use="required"/>
                                                                           </xs:extension>
                                                                           </xs:simpleContent>
                                                                           </xs:complexType>
                                                                           </xs:element>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                            <xs:attribute name="rend" type="xs:string" use="required"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="profileDesc">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="langUsage">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="language" maxOccurs="3">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute name="ident" use="required"/>
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="textClass">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="keywords">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="term" type="xs:string" maxOccurs="10"/>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="text">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="body">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="div" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:all>
                                                    <xs:element name="p" maxOccurs="unbounded">
                                                        <xs:complexType mixed="true">
                                                            <xs:all>
                                                                <xs:element ref="head" minOccurs="0"/>
                                                                <xs:element ref="lb" minOccurs="0" maxOccurs="unbounded"/>
                                                                <xs:element ref="add" minOccurs="0" maxOccurs="unbounded"/>
                                                                <xs:element ref="del" minOccurs="0" maxOccurs="unbounded"/>
                                                                <xs:element ref="unclear" minOccurs="0" maxOccurs="unbounded"/>
                                                                <xs:element ref="fw" minOccurs="0" maxOccurs="unbounded"/>
                                                                <xs:element ref="note" minOccurs="0" maxOccurs="unbounded"/>
                                                                <xs:element ref="term" minOccurs="0" maxOccurs="unbounded"/>
                                                                <xs:element ref="persName" minOccurs="0" maxOccurs="unbounded"/>
                                                                <xs:element ref="placeName" minOccurs="0" maxOccurs="unbounded"/>
                                                                <xs:element ref="orgName" minOccurs="0" maxOccurs="unbounded"/>
                                                                <xs:element ref="lg" minOccurs="0" maxOccurs="unbounded"/>
                                                            </xs:all>
                                                            <xs:attribute name="n" use="required"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:all>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="head">
        <xs:complexType mixed="true">
            <xs:all>
                <xs:element ref="lb" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="add" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="del" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="unclear" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="fw" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="note" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="term" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="persName" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="placeName" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="orgName" minOccurs="0" maxOccurs="unbounded"/>
            </xs:all>
        </xs:complexType>
    </xs:element>
    <xs:element name="term">
        <xs:complexType mixed="true">
            <xs:all>
                <xs:element ref="lb" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="add" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="del" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="unclear" minOccurs="0" maxOccurs="unbounded"/>
            </xs:all>
            <xs:attribute name="id" type="xs:ID" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="persName">
        <xs:complexType mixed="true">
            <xs:all>
                <xs:element ref="lb" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="add" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="del" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="unclear" minOccurs="0" maxOccurs="unbounded"/>
            </xs:all>
            <xs:attribute name="ref" type="xs:string" use="optional"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="placeName">
        <xs:complexType mixed="true">
            <xs:all>
                <xs:element ref="lb" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="add" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="del" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="unclear" minOccurs="0" maxOccurs="unbounded"/>
            </xs:all>
        </xs:complexType>
    </xs:element>
    <xs:element name="orgName">
        <xs:complexType mixed="true">
            <xs:all>
                <xs:element ref="lb" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="add" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="del" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="unclear" minOccurs="0" maxOccurs="unbounded"/>
            </xs:all>
        </xs:complexType>
    </xs:element>
    <xs:element name="date" type="xs:string"/>
    <xs:element name="lg">
        <xs:complexType>
            <xs:all>
                <xs:element ref="l" maxOccurs="unbounded"/>
            </xs:all>
        </xs:complexType>
    </xs:element>
    <xs:element name="l">
        <xs:complexType mixed="true">
            <xs:all>
                <xs:element ref="lb" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="add" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="del" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="unclear" minOccurs="0" maxOccurs="unbounded"/>
            </xs:all>
        </xs:complexType>
    </xs:element>
    <xs:element name="unclear">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="reason" type="xs:string" use="optional"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="lb">
        <xs:complexType/>
    </xs:element>
    <xs:element name="add" type="xs:string"/>
    <xs:element name="del" type="xs:string"/>
    <xs:element name="fw">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="type" type="xs:string" use="required"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="note">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="type" type="xs:string" use="required"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== AlexanderLasch/MKNetwork/00882_04.xml
<?xml version='1.0' encoding='UTF-8'?>
<TEI xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="../wikiversum_schema.xsd">
  <teiHeader>
    <fileDesc>
      <titleStmt>
        <title>4. Br. Layriz Rede vor dem Liebesmahl der Kinder und Societaets-Geschwister in Hennersdorf, am Christabend ... d. 24. Dec.</title>
        <editor>Evangelische Brüder-Unität</editor>
        <respStmt>
          <resp>XML-Schema and Header compiled by</resp>
          <name>Svetlana Yakutina</name>
          <name>Karina Söhl</name>
        </respStmt>
        <respStmt>
          <resp>Transcription from eScriptorium compiled by</resp>
          <name>Theresa Becker</name>
        </respStmt>
        <respStmt>
          <resp>Text Normalization</resp>
          <name>Navin Jamo</name>
        </respStmt>
        <respStmt> 
          <resp>Glossary compiled by</resp>
          <name>Karina Söhl</name>
          <name>Svetlana Yakutina</name>
        </respStmt>
      </titleStmt>
      <extent>
        <measure unit="pages">3</measure>
      </extent>
      <publicationStmt>
        <publisher>Evangelische Brüder-Unität, Herrnhuter Brüdergemeine</publisher>
        <pubPlace>Herrnhut</pubPlace>
        <date>1807</date>
        <idno type="Index-ID" source="https://zenodo.org/records/8228850">882</idno>
      </publicationStmt>
      <seriesStmt>
        <title>Erster Theil der Gemein-Nachrichten 1807</title>
        <biblScope unit="pages">378-380</biblScope>
        <idno type="shelfmark">GN.A. 355.</idno>
      </seriesStmt>
      <sourceDesc>
        <bibl>Erster Theil der Gemein-Nachrichten 1807. - GN.A.355 Nachrichten aus der Brüder-Gemeine</bibl>
        <msDesc rend="Handschrift">
          <msIdentifier>
            <institution> Unitätsarchiv Herrnhut </institution>
            <idno type="URN">urn:nbn:de:bsz:14-db-id17450503533</idno>
            <idno type="PURL">http://digital.slub-dresden.de/id1745050353</idno>
            <idno type="shelfmark"> GN.A. 355 </idno>
          </msIdentifier>
        </msDesc>
      </sourceDesc>
    </fileDesc>
    <profileDesc>
      <langUsage>
        <language ident="deu">German</language>
      </langUsage>
      <textClass>
        <keywords>
          <term>Religion</term>
          <term>Rede</term>
          <term>Predigt</term>
          <term>Weihnachten</term>
          <term>Hennersdorf</term>
        </keywords>
      </textClass>
    </profileDesc>
  </teiHeader>
  <text>
    <body>
      <div>
        <p n="378">
          <lb/> <head>4.) br. <persName>Layriz</persName> Rede vor dem 
            LiebesMahl der Kinder und 
            Societaets⸗ Geschwister in <placeName>Henners⸗
            dorf</placeName>, am Chriſtabend
          <unclear>[?]</unclear> d. 24. Dec.</head> 
           
          <lb/>Geſ: Biß Willkom̄en du edler 
          <lb/>Gaſt <unclear>[p?]</unclear> Ach mein herzliebes Jeſulein  
          <lb/>mach dir ein rein ſanft bettelein  
          <lb/>zu
          ruhn in meines Herzens⸗Schrein <unclear>[ff?]</unclear>  
          <lb/>Wen̄ wir uns an einem solchen  
          <lb/>Feſttage, wie die Chriſt<unclear>[N?]</unclear>acht iſt,  
          <lb/>verſam̄len, ſo iſt
          unſers Herzens  
          <lb/>Wunſch, daß uns die große  
          <lb/>Sache, deren Andencken wir  
          <lb/>feyren, vom heiligen Griſt ſo  
          <lb/>neu, so lebendig und
          kräftig  
          <lb/>im Herzen gemacht werden  
          <lb/>möge, als wen̄ wir vor 1776  
          <lb/>Jahren mit dabey geweſen wären.  
          <lb/>Man kans auch würcklich der
           
          <lb/>Gnaden⸗ Arbeit des heiligen  
          <lb/>Geiſtes nachrühmen, daß wen̄  
          <lb/>Er Herzen findet, denen damit  
          <lb/>gedient iſt, einen tiefen, neuen
           
          <lb/>und lebendigen Eindruck davon  
          <lb/>zu bekom̄en, Er ihnen solchen gerne  
          <lb/>ſchenckt. Er kan und will es auch th<unclear>[un?]</unclear>.  
          <lb/>Er kan uns
          die große Geſchichte  
          <lb/><fw type="catch">im </fw></p>
        <p n="379">
           
          <lb/>im Herzen ſo abmahlen, daß wir  
          <lb/>eben denſelben Eindruck von  
          <lb/>der Geburt unſers lieben Herrn  
          <lb/>und Heilands davon tragen, als
           
          <lb/>wen̄ wir mit den Hirten in  
          <lb/>den Stall zu <placeName>Bethlehem</placeName> gegan⸗  
          <lb/>gen wären, und das Jeſus⸗  
          <lb/>Kindlein in der Krippr in den
           
          <lb/>Windlein gefunden und geſehen  
          <lb/>hätten.  
          <lb/>Der Zweck warum wir jezo  
          <lb/>hier beyſam̄en ſind iſt daher,  
          <lb/>daß der heilige Geiſt
          die große  
          <lb/>Geſchichte dergleichen nicht vorge⸗  
          <lb/>kom̄en iſt, ſeit dem die Welt ſteht,  
          <lb/>und auch nicht wieder vorkom̄en  
          <lb/>wird,
          daß nehmlich Gottes Sohn  
          <lb/>als ein armes Menſchen Kind zur  
          <lb/><unclear>[W?]</unclear>elt geboren worden iſt, allen  
          <lb/>unſern Herzen ſo neu, ſo lebendig
           
          <lb/>und kräftig machen möge, als  
          <lb/>wenn ſie erſt heute geſchehen,  
          <lb/>und ein jedes von uns mit dabey  
          <lb/>geweſen wäre, und hätte das
           
          <lb/>Jeſulein in der Krippe in Wind⸗  
          <lb/>lein geſehen, ſeine zarte Hände  
          <lb/>geküßt, und Jhn als unſern Herrn  
          <lb/>und Gott angebetet.
        </p>
        <p n="380">
           
          <lb/>Das wünſchen wir nicht nur uns  
          <lb/>überhaupt, ſondern auch beſonders  
          <lb/>unſern Brüdern, wünſchen wir daß  
          <lb/>ſie gleich
          in ihrem erſten zarten Jah⸗  
          <lb/>ren einen tiefen Eindruck von ihres  
          <lb/>lieben Jeſuleins geburt bekom̄en und  
          <lb/>den ſeligſten Genuß
          davon haben  
          <lb/>mögen, daß Er ihr Brüderlein wor⸗  
          <lb/>den, eben ſo wie wir fleiſch  
          <lb/>und blut an ſich genom̄en, u. da⸗  
          <lb/>durch eine
          ewige Errettung und  
          <lb/>Erlöſung für uns zu wege ge⸗  
          <lb/>bracht hat. Wenn wir alle mit⸗  
          <lb/>einander, alt und jung, groß  
          <lb/>und klein,
          mit einem ſolchen  
          <lb/>Herzen beyſam̄en sind, und  
          <lb/>der Heilige Geiſt findet unſer  
          <lb/>Herzen offen daß Er uns  
          <lb/>das große Geheimniß
          von  
          <lb/>unſeres Schöpfers Menſchwerdung  
          <lb/>und geburt recht neu machen  
          <lb/>kan; dan̄ werden wir ein recht  
          <lb/>ſeliges Liebesmahl haben.
           
          <lb/>Geſ: So halten wir dan̄ Liebes⸗  
          <lb/>mahl beymlieben Jeſus⸗ Kindlein u.  
          <lb/>freu&amp;#x27;n uns unſrer Gnadenwahl  
          <lb/>bey Jhm in
          seinen Windlein, kom,  
          <lb/>blutiger Jm anuel, u. laß uns <unclear>[dein genießen?]</unclear> 
          <lb/><fw type="catch">5.) br.</fw> 
        </p>
      </div>
    </body>
  </text>
</TEI>

=== AlexanderLasch/MKNetwork/00408_04.xml
<?xml version='1.0' encoding='UTF-8'?>
<TEI xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="../wikiversum_schema.xsd">
  <teiHeader>
    <fileDesc>
      <titleStmt>
        <title>No. 30. des Ersten Theils der Gemein-Nachrichten 1807</title>
        <editor>Evangelische Brüder-Unität</editor>
        <respStmt>
          <resp>XML-Schema and Header compiled by</resp>
          <name>Svetlana Yakutina</name>
          <name>Karina Söhl</name>
        </respStmt>
        <respStmt>
          <resp>Transcription from eScriptorium compiled by</resp>
          <name>Sabine Hollmann</name>
        </respStmt>
        <respStmt>
          <resp>Text Normalization</resp>
          <name>Natalia Hanke</name>
        </respStmt>
        <respStmt> 
          <resp>Glossary compiled by</resp>
          <name>Karina Söhl</name>
          <name>Svetlana Yakutina</name>
        </respStmt>
      </titleStmt>
      <extent>
        <measure unit="pages">1</measure>
      </extent>
      <publicationStmt>
        <publisher>Evangelische Brüder-Unität, Herrnhuter Brüdergemeine</publisher>
        <pubPlace>Herrnhut</pubPlace>
        <date>1807</date>
        <idno type="Index-ID" source="https://zenodo.org/records/8228850">408</idno>
      </publicationStmt>
      <seriesStmt>
        <title>Erster Theil der Gemein-Nachrichten 1807</title>
        <biblScope unit="pages">908</biblScope>
        <idno type="shelfmark">GN.A. 355.</idno>
      </seriesStmt>
      <sourceDesc>
        <bibl>Erster Theil der Gemein-Nachrichten 1807. - GN.A.355 Nachrichten aus der Brüder-Gemeine</bibl>
        <msDesc rend="Handschrift">
          <msIdentifier>
            <institution> Unitätsarchiv Herrnhut </institution>
            <idno type="URN">urn:nbn:de:bsz:14-db-id17450503533</idno>
            <idno type="PURL">http://digital.slub-dresden.de/id1745050353</idno>
            <idno type="shelfmark"> GN.A. 355 </idno>
          </msIdentifier>
        </msDesc>
      </sourceDesc>
    </fileDesc>
    <profileDesc>
      <langUsage>
        <language ident="deu">German</language>
      </langUsage>
      <textClass>
        <keywords>
          <term>Reisebericht</term>
          <term>Überschrift</term>         
          <term>Lettland</term>
        </keywords>
      </textClass>
    </profileDesc>
  </teiHeader>
  <text>
    <body>
      <div>
        <p n="NA">
          <lb/><head>No 30. des Erſten Theils der Gemein⸗Nachrichten 1807.</head>
        </p>
      </div>
    </body>
  </text>
</TEI>
